---
- hosts: srvs
  become: yes
  vars_files:
    - config.yml
  roles: 
    - ruby

- hosts: local
  become: yes
  roles:
    - common
    - ntp

- hosts: srvs
  become: yes
  vars_files:
    - config.yml
  roles: 
    - common
    - git
    - ntp
    - ruby


