---
# - name: Install Rubi-Build
#   shell: PREFIX=/opt/ruby /opt/ruby/rbenv/plugins/ruby-build/install.sh

- name: Install Ruby-build
  poll: 30
  async: 10800
  shell: /bin/bash -lc "PREFIX=/opt/ruby /opt/ruby/rbenv/plugins/ruby-build/install.sh"
  args:
    executable: /bin/bash

- name: Install Ruby
  poll: 30
  async: 10800
  shell: bash -lc "rbenv install --skip-existing {{ ruby_version }}"
  args:
    executable: /bin/bash

- name: Apply Ruby Version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  args:
    executable: /bin/bash

- name: Install Basic Gems (bundler)
  gem:
    name: bundler
    user_install: no
    executable: /opt/ruby/shims/gem

- name: Install Basic Gems (pry)
  gem:
    name: pry
    user_install: no
    executable: /opt/ruby/shims/gem

- name: Install Basic Gems (pry-rails)
  gem:
    name: pry-rails
    user_install: no
    executable: /opt/ruby/shims/gem


