---
# - name: Install Rubi-Build
#   shell: PREFIX=/opt/ruby /opt/ruby/rbenv/plugins/ruby-build/install.sh

- name: Install Ruby-build
  poll: 30
  async: 10800
  shell: bash -lc "PREFIX=/opt/ruby /opt/ruby/rbenv/plugins/ruby-build/install.sh"

- name: Install Ruby
  poll: 30
  async: 10800
  shell: bash -lc "rbenv install --skip-existing {{ ruby_version }}"
  # shell: /bin/bash /home/ansible/.profile && rbenv install --skip-existing {{ ruby_version }}

- name: Apply Ruby Version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  # args:
  #   executable: /bin/bash -l

- name: Install Basic Gems [bundler, pry]
  gem:
    name: "[ 'bundler', 'pry' ]"
    user_install: no
    executable: /opt/ruby/rbenv/shims/gem

