---
# - name: Install Rubi-Build
#   shell: PREFIX=/opt/ruby /opt/ruby/rbenv/plugins/ruby-build/install.sh

- name: Install Ruby
  shell: bash -lc "BASH_ENV=/etc/profile rbenv install --skip-existing {{ ruby_version }}"
  # shell: /bin/bash /home/ansible/.profile && rbenv install --skip-existing {{ ruby_version }}

- name: Apply Ruby Version
  shell: bash -lc "BASH_ENV=/etc/profile rbenv global {{ ruby_version }}"
  # args:
  #   executable: /bin/bash -l

- name: Install Basic Gems [bundler, pry]
  gem:
    name: [ 'bundler', 'pry' ]
    user_install: no
    executable: /opt/ruby/rbenv/shims/gem

