---
- name: install language-pack
  apt: 
    name: ['language-pack-ja', 'ibus-anthy', 'ibus-mozc']
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  register: install_language_pack
    
- name: update locale
  command: update-locale LANG="ja_JP.UTF-8"
  when: install_language_pack is changed
